version: '3'

services: 
  MySQL:
    image: mysql
    container_name: MySQL
    env_file: ./MySQL/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    restart: always
    volumes: 
      - datastore:/var/lib/mysql
      - ./MySQL/database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=MySQL
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
       - 8090:80
    volumes:
       - /sessions
    
volumes: 
  datastore:
    driver: local